# This file defines the basics that should always be used

global:
  # Make sure that set_text_variables is only applied during the kibot
  # run, but does not pollute the working copy afterwards
  restore_project: true
  pcb_finish: ENIG
  default_resistor_tolerance: 5

preflight:
  set_text_variables:
    - name: BOARD_REVISION
      # Take the board revision part of the tag, and check for modifications since
      command: |
        set -e
        TAG=$(git describe --tags --abbrev=0 || true)
        if [ -z "$TAG" ]; then echo "notag"; exit 0; fi
        echo -n $TAG | awk -F/ '{if (NF < 2 || NF > 3 || $2 == "") { print("Invalid tag format"); exit 1 } else { printf($2)}}'
        if ! git diff --quiet ${TAG}; then
          echo " — modified"
        fi
    - name: COMPONENTS_DATE
      # Take the components date part of the tag, and check for modifications since
      command: |
        set -e
        TAG=$(git describe --tags --abbrev=0 || true)
        if [ -z "$TAG" ]; then echo "notag"; exit 0; fi
        echo -n $TAG | awk -F/ '{printf($3)}'
        if ! git diff --quiet ${TAG}; then
          echo " — modified"
        fi
    - name: GIT_REVISION_INFO
      # Just include complete info on where this was generated from
      before: "Generated from git "
      command: git describe --tags --all --long --always --dirty

    - name: VARIANT
      # Put the current variant in a text var, so it can be referenced
      # from our custom sheet
      text: "%V"
