# This workflow handles all kinds of pushes. What happens exactly is
# decided by the generic workflow that we delegate to.
name: Workflow

on:
  push:
    tags:
     - '**' # Use a double *, to also match /
    branches:
     - '*'
  pull_request:

jobs:
  workflow:
    permissions:
      # Allow creating releases
      contents: write
    uses: matthijskooijman/PCB-workflows/.github/workflows/dispatcher.yml@dev
    secrets: inherit
    permissions:
      # Allow write access to create a release
      contents: write
